<a href="https://colab.research.google.com/github/ImaduddinAhmedMohammed/ImaduddinAhmed_DTSC5502_Spring2024/blob/main/DTSC_5502_Homework_Assignment_002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install numpy

In [83]:
import numpy as np
Y= np.array([ [1],[0],[1],[4],[3],[2],[5],[6],[9],[13],[15],[16] ])
print("Y is:")
print(Y)
print("")
print(Y.shape)
print("")
X = np.array([ [1,1,1],
               [1,2,1],
               [1,2,2],
               [1,3,2],
               [1,5,4],
               [1,5,6],
               [1,6,5],
               [1,7,4],
               [1,10,8],
               [1,11,7],
               [1,11,9],
               [1,12,10] ])
print("X is:")
print("")
print(X)
print("")
print(X.shape)
print("")
XT=np.transpose(X)
print("X Transpose:")
print("")
print(XT)
print(XT.shape)
print("")
X_new=np.dot(XT,X)
print("The multiplication of X transpose and X is:")
print('')
print(X_new)
print(f"The shape of XTranspose*X is:\n",X_new.shape)
print('')
X_newinv=np.linalg.inv(X_new)
print('')
B=np.dot(X_newinv,XT)
Beta=np.dot(B,Y)
print(f"The Values of Beta are:\n",Beta)
print('')
print(Beta.shape)
B0=Beta[0]
B1=Beta[1]
B2=Beta[2]
print(f"The Value of B0 is: ",B0)
print(f"The Value of B1 is: ",B1)
print(f"The Value of B2 is: ",B2)
print("")
print(f"The predicted value of Y is: \n Y_Predicted="+str(B0)+"+"+str(B1)+"X1"+"+"+str(B2)+"X2+ϵ")
print("")
print(f"The value of X is: \n X="+str(B1)+"X1"+"+"+str(B2)+"X2")
print("")
print(f"The predicted value of Y is:\n Y_predicted="+str(B0)+"+"+"X+ϵ")

Y is:
[[ 1]
 [ 0]
 [ 1]
 [ 4]
 [ 3]
 [ 2]
 [ 5]
 [ 6]
 [ 9]
 [13]
 [15]
 [16]]

(12, 1)

X is:

[[ 1  1  1]
 [ 1  2  1]
 [ 1  2  2]
 [ 1  3  2]
 [ 1  5  4]
 [ 1  5  6]
 [ 1  6  5]
 [ 1  7  4]
 [ 1 10  8]
 [ 1 11  7]
 [ 1 11  9]
 [ 1 12 10]]

(12, 3)

X Transpose:

[[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  2  3  5  5  6  7 10 11 11 12]
 [ 1  1  2  2  4  6  5  4  8  7  9 10]]
(3, 12)

The multiplication of X transpose and X is:

[[ 12  75  59]
 [ 75 639 497]
 [ 59 497 397]]
The shape of XTranspose*X is:
 (3, 3)


The Values of Beta are:
 [[-2.2630379 ]
 [ 1.54972927]
 [-0.2385295 ]]

(3, 1)
The Value of B0 is:  [-2.2630379]
The Value of B1 is:  [1.54972927]
The Value of B2 is:  [-0.2385295]

The predicted value of Y is: 
 Y_Predicted=[-2.2630379]+[1.54972927]X1+[-0.2385295]X2+ϵ

The value of X is: 
 X=[1.54972927]X1+[-0.2385295]X2

The predicted value of Y is:
 Y_predicted=[-2.2630379]+X+ϵ
