<a href="https://colab.research.google.com/github/ImaduddinAhmedMohammed/ImaduddinAhmed_DTSC5502_Spring2024/blob/main/Gradient_descent_5502.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
Y= np.array([1,0,1,4,3,2,5,6,9,13,15,16])
print(Y)
print("")
print(Y.shape)
print("")
X = np.array([ [1,1,1],
               [1,2,1],
               [1,2,2],
               [1,3,2],
               [1,5,4],
               [1,5,6],
               [1,6,5],
               [1,7,4],
               [1,10,8],
               [1,11,7],
               [1,11,9],
               [1,12,10] ])
print("X is:")
print("")
print(X)
print("")
print(X.shape)
print("")
XT=np.transpose(X)
print("X Transpose:")
print("")
print(XT)
print(XT.shape)
print("")

def linear_regression(beta,X,Y):      #defining a function for linear regression to calculate the loss
  Y_pred= X @ beta
  loss = np.sum((Y_pred - Y) ** 2)
  return loss

def gradient_descent(X,Y,learning_rate,num_iterations): #defining a function for gradient descent
  n,p=X.shape
  beta=np.zeros(p)                                      #intitalizing the values in beta matrix to 0
  Beta=beta.reshape(-1, 1)
  print("shape of beta is: ",Beta.shape)
  best_loss=np.inf                                      #initializing the best loss to infintite and then update it later
  best_beta=np.zeros(p)                                 #initializing the values in best beta matrix to 0
  for i in range(num_iterations+1):                     #iterating a loop to execute and calculate the best beta and loss at every set of beta values
    Y_pred=np.dot(X,beta)
    gradient = 2 * X.T @ (Y_pred - Y) / n
    beta = beta-(learning_rate*gradient)
    current_loss=linear_regression(beta,X,Y)            # calling the linear_regression function to find the loss
    if current_loss<best_loss:                          # comparing the best loss and current loss and updating the loss according to the condition
      best_loss=current_loss
      best_beta=beta
    if i<10 or i>num_iterations-10:                     # setting condition to print only the first 10 values and the last 10 values
      print("Iteration:",i,"\tBeta values:",beta)
      print("Best loss:",current_loss)
  print("shape of gradient is:",gradient.shape)
  print("shape of y pred is:",Y_pred.shape)
  print("shape of y pred - Y is:",(Y_pred-Y).shape)
  return{'beta': best_beta, 'loss': best_loss}

learning_rate= 0.0001                                   #setting the learning rate
num_iterations=30000                                    #setting the number of iterations
result=gradient_descent(X,Y,learning_rate,num_iterations)





[ 1  0  1  4  3  2  5  6  9 13 15 16]

(12,)

X is:

[[ 1  1  1]
 [ 1  2  1]
 [ 1  2  2]
 [ 1  3  2]
 [ 1  5  4]
 [ 1  5  6]
 [ 1  6  5]
 [ 1  7  4]
 [ 1 10  8]
 [ 1 11  7]
 [ 1 11  9]
 [ 1 12 10]]

(12, 3)

X Transpose:

[[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  2  3  5  5  6  7 10 11 11 12]
 [ 1  1  2  2  4  6  5  4  8  7  9 10]]
(3, 12)

shape of beta is:  (3, 1)
Iteration: 0 	Beta values: [0.00125    0.0117     0.00903333]
Best loss: 796.8220357944444
Iteration: 1 	Beta values: [0.00247624 0.02319901 0.01790875]
Best loss: 771.5422005482003
Iteration: 2 	Beta values: [0.00367914 0.0345005  0.02662899]
Best loss: 747.1296763701905
Iteration: 3 	Beta values: [0.00485909 0.04560789 0.03519673]
Best loss: 723.5547028377974
Iteration: 4 	Beta values: [0.0060165  0.05652455 0.04361462]
Best loss: 700.7885407114618
Iteration: 5 	Beta values: [0.00715175 0.06725377 0.05188524]
Best loss: 678.803436894359
Iteration: 6 	Beta values: [0.00826523 0.07779879 0.06001115]
Best loss: 657.572